spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://alphacashier-asp-db-instance.ctnru7tj6gzl.ap-northeast-2.rds.amazonaws.com:4406/PmKioskAWS?allowMultiQueries=true&useSSL=false&autoReconnect=true&useUnicode=yes;
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: pass_softlogic
    hikari:
      maximumPoolSize: 1000
      connectionTestQuery: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties: 
      hibernate:
        format_sql: true 
             
mybatis: 
  mapper-locations: classpath:mybatis/mapper/*.xml
 
cloud:
  aws:
    credentials:
      accesskey: AKIA36XY6AUNW6W5FG6E
      secretkey: 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   
    region:
      static: ap-northeast-2c
      
server:
  port: 13270
  servlet:
    context-path: /
    
# 실서버 master
#url: jdbc:mysql://alphacashier-asp-db-instance.ctnru7tj6gzl.ap-northeast-2.rds.amazonaws.com:4406/PmKioskAWS?allowMultiQueries=true&useSSL=false&autoReconnect=true&useUnicode=yes;
#driver-class-name: com.mysql.cj.jdbc.Driver
#username: admin
#password: pass_softlogic

# 사내 테스트 PC develop
#url: jdbc:mysql://222.98.245.65:3306/PmKioskAWS?allowMultiQueries=true&useSSL=false&autoReconnect=true&useUnicode=yes;
#driver-class-name: org.mariadb.jdbc.Driver
#username: root
#password: pass_posmania4906!

# AWS 사내 계정  develop
#url: jdbc:mysql://lightsolution-aws-db-instance.clvvluyg0a7d.ap-northeast-2.rds.amazonaws.com:3306/PmKioskAWS?allowMultiQueries=true&useSSL=false&autoReconnect=true&useUnicode=yes;
#driver-class-name: com.mysql.cj.jdbc.Driver
#username: admin
#password: pass_softlogic


